config/routes.rb
Rails.application.routes.draw do
  resources :titles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "titles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/title.rb
class Title < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_title, only: %i[ show edit update destroy ]

  # GET /titles or /titles.json
  def index
    @titles = Title.all
  end

  # GET /titles/1 or /titles/1.json
  def show
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles or /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to title_url(@title), notice: "Title was successfully created." }
        format.json { render :show, status: :created, location: @title }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1 or /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to title_url(@title), notice: "Title was successfully updated." }
        format.json { render :show, status: :ok, location: @title }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1 or /titles/1.json
  def destroy
    @title.destroy

    respond_to do |format|
      format.html { redirect_to titles_url, notice: "Title was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def title_params
      params.require(:title).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railway</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/titles/_form.html.erb
<%= form_with(model: title) do |form| %>
  <% if title.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
        <% title.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/titles/_title.html.erb
<div id="<%= dom_id title %>">
  <p>
    <strong>Content:</strong>
    <%= title.content %>
  </p>

</div>

app/views/titles/edit.html.erb
<h1>Editing title</h1>

<%= render "form", title: @title %>

<br>

<div>
  <%= link_to "Show this title", @title %> |
  <%= link_to "Back to titles", titles_path %>
</div>

app/views/titles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Titles</h1>

<div id="titles">
  <% @titles.each do |title| %>
    <%= render title %>
    <p>
      <%= link_to "Show this title", title %>
    </p>
  <% end %>
</div>

<%= link_to "New title", new_title_path %>

app/views/titles/new.html.erb
<h1>New title</h1>

<%= render "form", title: @title %>

<br>

<div>
  <%= link_to "Back to titles", titles_path %>
</div>

app/views/titles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @title %>

<div>
  <%= link_to "Edit this title", edit_title_path(@title) %> |
  <%= link_to "Back to titles", titles_path %>

  <%= button_to "Destroy this title", @title, method: :delete %>
</div>